name: docs

# declare default permissions
permissions: read-all

on:
  # enable manual run via GitHub UI
  workflow_dispatch:
  
  # enable trigger via remote call webhook
  repository_dispatch:
    types: update-docs

  # enable run on "standard" updates to main branch
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

env:
  CORE: ./core
  DOCS: ./docs
  DIST: ${{DOCS}}/dist
  SITE: ${{DOCS}}/site
  WORK: ${{DOCS}}/build/work

jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: defenseunicorns/pepr-docs
          path: ${{DOCS}}

      - uses: actions/checkout@v4
        with:
          repository: defenseunicorns/pepr
          path: ${{CORE}}
          fetch-depth: 0  # pull history to get version tags

      - name: Get current defenseunicorns/pepr release
        id: get_current_pepr_release_version
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: defenseunicorns/pepr
          excludes: prerelease, draft

      - name: Build the docs!
        run: |
          SITE=$(realpath "$SITE")
          CORE=$(realpath "$CORE")
          cd "$DOCS"
          npm ci
          npm --workspace build run now -- --site "$SITE" --core "$CORE"

      - name: Commit new docs back to source!
        run: |
          ls -la "$DIST"

      # - name: Publish the site!
      #   run: |
      #     DIST=$(realpath ./docs/dist)
      #     ls -la "$DIST"